export const mockActivities = [
    {
        id: "1",
        type: "invitation_request",
        title: "Invitation Request",
        description: "Hi Om, I'm building consultative AI...",
        timestamp: new Date(),
        status: "completed",
    },
    {
        id: "2",
        type: "connection_status",
        title: "Connection Status",
        description: "Check connection status",
        timestamp: new Date(),
        status: "pending",
    },
    {
        id: "3",
        type: "message",
        title: "Connection Acceptance Message",
        description: "Message: Awesome to connect, Dilbag! Allow me...",
        timestamp: new Date(),
        status: "pending",
    },
    {
        id: "4",
        type: "follow_up",
        title: "Follow-up 1",
        description: "Message: Hey, did you get a chance to go thru...",
        timestamp: new Date(),
        status: "pending",
    },
    {
        id: "5",
        type: "follow_up",
        title: "Follow-up 2",
        description: "Message: Hi Dilbag, just following up on my m...",
        timestamp: new Date(),
        status: "pending",
    },
    {
        id: "6",
        type: "message",
        title: "Replied",
        description: "No reply",
        timestamp: new Date(),
        status: "completed",
    },
];