name: CI Checks

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checks out your repository code so the job can access it
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. Sets up the correct version of Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Use the Node.js version you are developing with
          cache: "npm" # Caches npm packages for faster subsequent runs

      # 3. Installs project dependencies
      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Vercel Action
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{secrets.VERCEL_TOKEN}}
          vercel-org-id: ${{secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{secrets.VERCEL_PROJECT_ID}}
          working-directory: ./
          vercel-args: "--prod"